Algoritmo "area_triangulo"
// Função : calcular a area do triangulo
// Autor : Maria Eduarda Santo Silva
// Data : 02/03
Var
// Seção de Declarações das variáveis
area,base,alt : real


Inicio
// entrega de dados
escreval("Digite a base do triangulo retangulo")
leia (base)

escreval("Digite a altura do triangulo retangulo")
leia (alt)

//processamento
area <- (base*alt)/2

//Saida
escreval ( "A area do triangulo retanguloe: " ,area, "m2" )

Fimalgoritmo