Algoritmo "area_retangulo"
//Função : calcular a area do retangulo
// Autor : Maria Eduarda Santo Silva
// Data : 02/03
Var
// Seção de Declarações das variáveis
area,base,alt : real


Inicio
// Entrada
escreval ("Digite a base do retangulo")
leia (base)

escreval(" Digite a altura do retangulo")
leia (alt)

//processamento
area <- base*alt

//Saida
escreval(" A area do retangulo e: " , area , "m2")

Fimalgoritmo